#!/bin/sh
# 
# splashtool – A simple tool for creating SYSLINUX splashes without fuss
# 
# Copyright © 2013, 2014  Mattias Andrée (maandree@member.fsf.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


in="$(realpath "$1")"
out="$(realpath "$2")"
d="$(dirname "$(realpath "$0")")"

# Remove all information we do not need.
trim ()
{
    sed -e 's/\t/ /g' | sed -e '/^[ \t]*\(#\|$\)/d' -e 's/ #.*$//' -e 's/^ *//' -e 's/ *$//' |
	awk 'BEGIN { text = 0; }
             { t=tolower($1);
               if (t=="text") text+=1;
               if (t=="timeout" || t=="menu" || t=="font" || text==1) print $LINE;
               if (t=="endtext") text+=1;
             }'
}

cd "$(dirname "$1")"
trim < "$in" | "$d"/parse.py | java -cp "$d" Assemble "$out" "$3"

